### ISSUE TITLE
Bug: Scalding jobs broken in HDFS mode

### ISSUE THREAD

**Issue by hgrano** [CommBank/grimlock#92]
Grimlock scalding jobs fail when run in non-local mode (i.e. on a HDFS cluster). This affects Grimlock version 0.7.7. When running this script https://github.com/CommBank/grimlock/blob/minimal-scalding-bug/grimlock-examples/src/main/scala/commbank/grimlock/scalding/run-basic-operations.sh I get a
```
Exception in thread "main" java.lang.StackOverflowError
	at com.twitter.chill.KryoBase.isJavaLambda(KryoBase.scala:47)
	at com.twitter.chill.KryoBase.getRegistration(KryoBase.scala:50)
	at com.esotericsoftware.kryo.util.DefaultClassResolver.writeClass(DefaultClassResolver.java:97)
	at com.esotericsoftware.kryo.Kryo.writeClass(Kryo.java:517)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:76)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
	at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:552)
	at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:80)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:518)
```

**Comment by hgrano** [comment]
From testing, I can confirm that Grimlock 0.7.6 is OK, but Grimlock 0.7.7 is broken @poojke @tgibson5463 . I'll work on trying to keep the TypeTag but delaying evaluation until after serialisation

**Comment by tgibson5463** [comment]
@hgrano can this be closed now?

**Comment by tgibson5463** [comment]
It would be nice if we could add unit tests that check for working behaviour in scalding environment

**Comment by hgrano** [comment]
Yes I believe this should fix the problem. 100% agree we need tests which test Grimlock in a more "realistic" environment

**Comment by hgrano** [comment]
Closed by https://github.com/CommBank/grimlock/pull/93
